const ammoCountClass1 = 6,
    bulletSpeedClass1 = 6,
    playerSpeedClass1 = 1.9,
    reloadTimeMsClass1 = 2400,
    reloadAmmoClass1 = 6,
    collisionBulletClass1 = true,
    playerTextureClass1 = "playerClass1.png",
    bulletTextureClass1 = "bulletTextureClass1.png",
    playerDeadTextureClass1 = "player1DeadTexture.png",
    bulletKillRangeClass1 = 25,
    playerHPClass1 = 50,
    bulletDamageClass1 = 10,

    ammoCountClass2 = 8,
    bulletSpeedClass2 = 3.5,
    playerSpeedClass2 = 2.1,
    reloadTimeMsClass2 = 1200,
    reloadAmmoClass2 = 10,
    collisionBulletClass2 = true,
    playerTextureClass2 = "playerClass2.png",
    bulletTextureClass2 = "bulletTextureClass2.png",
    playerDeadTextureClass2 = "player1DeadTexture.png",
    bulletKillRangeClass2 = 20,
    playerHPClass2 = 20,
    bulletDamageClass2 = 4,


    ammoCountClass3 = 1,
    bulletSpeedClass3 = 4,
    playerSpeedClass3 = 1.5,
    reloadTimeMsClass3 = 540,
    reloadAmmoClass3 = 1,
    collisionBulletClass3 = true,
    playerTextureClass3 = "playerClass3.png",
    bulletTextureClass3 = "bulletTextureClass3.png",
    playerDeadTextureClass3 = "player1DeadTexture.png",
    bulletKillRangeClass3 = 10,
    playerHPClass3 = 25,
    bulletDamageClass3 = 5,


    ammoCountClass4 = 1,
    bulletSpeedClass4 = 20,
    playerSpeedClass4 = 1.4,
    reloadTimeMsClass4 = 5000,
    reloadAmmoClass4 = 1,
    collisionBulletClass4 = false,
    playerTextureClass4 = "playerClass4.png",
    bulletTextureClass4 = "bulletTextureClass4.png",
    playerDeadTextureClass4 = "player1DeadTexture.png",
    bulletKillRangeClass4 = 200,
    playerHPClass4 = 5,
    bulletDamageClass4 = 50;



const enemySpeed = 2.5,
      enemyHP = 10,
      enemyDamage = 10,
      enemyAttackCooldown = 1000,
      enemySpawnPeriod = 1600;
